### ISSUE TITLE
Documentation: `END;` must be removed.

### ISSUE THREAD

**Issue by fjf2002** [theory/pgtap#272]
In your documentation, in
```sql
CREATE OR REPLACE FUNCTION test_user(
) RETURNS SETOF TEXT AS $$
   SELECT is( nick, 'theory', 'Should have nick') FROM users;
END;
$$ LANGUAGE sql;
```

The line `END;` must be removed.

**Comment by theory** [comment]
That was fixed by #208 and released way back in 1.1.0 in late 2019.

**Comment by fjf2002** [comment]
... but still present in https://pgtap.org/documentation.html !?

**Comment by theory** [comment]
Ah, thanks, yeah, we never updated the docs for v1.1.0 🤦🏻  Fixed in 4161e606.
